// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWJ6z9BcYFsJ8HJIIMA0EznuSw4n6ywM',
    appId: '1:1045664607661:web:1c559dbe10c4bce1ba8524',
    messagingSenderId: '1045664607661',
    projectId: 'flutter-module-3',
    authDomain: 'flutter-module-3.firebaseapp.com',
    storageBucket: 'flutter-module-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUlXgKVRo649F0u6YoWPFjuzSIY6Uj-jQ',
    appId: '1:1045664607661:android:5d651c7fe5981523ba8524',
    messagingSenderId: '1045664607661',
    projectId: 'flutter-module-3',
    storageBucket: 'flutter-module-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfshGqIe6zKEX2nzg03CRpbIPWm0pQ_k',
    appId: '1:1045664607661:ios:cae1a820bea39626ba8524',
    messagingSenderId: '1045664607661',
    projectId: 'flutter-module-3',
    storageBucket: 'flutter-module-3.firebasestorage.app',
    iosBundleId: 'com.example.flutterModule3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEfshGqIe6zKEX2nzg03CRpbIPWm0pQ_k',
    appId: '1:1045664607661:ios:cae1a820bea39626ba8524',
    messagingSenderId: '1045664607661',
    projectId: 'flutter-module-3',
    storageBucket: 'flutter-module-3.firebasestorage.app',
    iosBundleId: 'com.example.flutterModule3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjWJ6z9BcYFsJ8HJIIMA0EznuSw4n6ywM',
    appId: '1:1045664607661:web:20b691571a094782ba8524',
    messagingSenderId: '1045664607661',
    projectId: 'flutter-module-3',
    authDomain: 'flutter-module-3.firebaseapp.com',
    storageBucket: 'flutter-module-3.firebasestorage.app',
  );
}
